### PR TITLE
[GITHUB] Setup GitHub CI (#1)

### PR DESCRIPTION
**Pull request by apierg**
# Why is the change needed?
As mentioned in Issue #1, the CI is only implemented in the (internal) GitLab repository and not on the (public) Github one.

# What changes does the patch introduce?
Implements a CI pipeline as a GitHub workflow.

# How was this patch tested?
Manual review.

### CODE REVIEW

**Comment by mgaido91** [comment]
the change itself LGTM, however the CI failures seem valid errors due to different precisions. We have to fix the tests before merging this...

**Comment by mgaido91** [comment]
Can you open a MR on our gitlab to fix the issue with python versions > 3.8? @apierg @dennisfcc

**Comment by apierg** [comment]
> Can you open a MR on our gitlab to fix the issue with python versions > 3.8? @apierg @dennisfcc

I opened the MR.

**Comment by mgaido91** [comment]
Closes #1

**Pull request merged**
